export default [
  'ADDRESS_FIND',
  'ADDRESS_FIND_BY_ID',
  'ADDRESS_FIND_ONE',

  'CASH_SALE_FIND',
  'CASH_SALE_FIND_BY_ID',
  'CASH_SALE_FIND_ONE',

  'CLIENT_CREDIT_NOTE_FIND',
  'CLIENT_CREDIT_NOTE_FIND_BY_ID',
  'CLIENT_CREDIT_NOTE_FIND_ONE',

  'CLIENT_INVOICE_FIND',
  'CLIENT_INVOICE_FIND_BY_ID',
  'CLIENT_INVOICE_FIND_ONE',

  'CLIENT_ORDER_FIND',
  'CLIENT_ORDER_FIND',
  'CLIENT_ORDER_FIND_ONE',

  'EVENT_CATEGORY_FIND',
  'EVENT_CATEGORY_FIND_BY_ID',
  'EVENT_CATEGORY_FIND_ONE',

  'EVENT_FIND',
  'EVENT_FIND_BY_ID ',
  'EVENT_FIND_ONE',

  'LEDGER_ACCOUNT_FIND',
  'LEDGER_ACCOUNT_FIND_BY_ID',
  'LEDGER_ACCOUNT_FIND_ONE',

  'NOTE_FIND',
  'NOTE_FIND_BY_ID',
  'NOTE_FIND_ONE',
  'POSTING_FIND',
  'POSTING_FIND_BY_ID',
  'POSTING_FIND_ONE',

  'SUPPLIER_CREDIT_NOTE_FIND',
  'SUPPLIER_CREDIT_NOTE_FIND_BY_ID',
  'SUPPLIER_CREDIT_NOTE_FIND_ONE',

  'SUPPLIER_INVOICE_FIND',
  'SUPPLIER_INVOICE_FIND_BY_ID',
  'SUPPLIER_INVOICE_FIND_ONE',

  'SUPPLIER_ORDER_FIND',
  'SUPPLIER_ORDER_FIND_BY_ID',
  'SUPPLIER_ORDER_FIND_ONE',

  'USER_FIND',
  'USER_FIND_FIND_BY_ID',
  'USER_FIND_ONE'
];
